/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unpas.psi.tubes.view;


import com.mysql.jdbc.Statement;

import id.ac.unpas.psi.tubes.controller.BarangController;
import id.ac.unpas.psi.tubes.model.data.BarangModel;
import id.ac.unpas.psi.tubes.model.pojo.Barang;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SB604-15
 */
public class BarangFrame extends javax.swing.JFrame {
    BarangController con = new BarangController();
    private DefaultTableModel model;
    /**
     * Creates new form TabelMahasiswaFrame
     */
    public BarangFrame() throws SQLException {
        initComponents();
        populateDataToTable();
    }
    
    public void refreshTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        model.setRowCount(0);
        populateDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        lblMasuk = new javax.swing.JLabel();
        tfMasuk = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        lblHome = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfHarga = new javax.swing.JTextField();
        lblKeluar = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        tfKeluar = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblId.setText("ID Barang");

        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_BARANG", "NAMA_BARANG", "HARGA_BARANG", "TGL_MASUK", "TGL_KELUAR", "STOK_BARANG"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        lblMasuk.setText("Tgl Masuk");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        lblHome.setText("Home");
        lblHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblHomeActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jScrollPaneLayout = new javax.swing.GroupLayout(jScrollPane);
        jScrollPane.setLayout(jScrollPaneLayout);
        jScrollPaneLayout.setHorizontalGroup(
            jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScrollPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jScrollPaneLayout.createSequentialGroup()
                .addComponent(lblId)
                .addGap(26, 26, 26)
                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnTambah)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jScrollPaneLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jScrollPaneLayout.setVerticalGroup(
            jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScrollPaneLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMasuk)
                    .addComponent(tfMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah)))
        );

        lblNama.setText("Nama Barang");

        lblHarga.setText("Harga");

        lblKeluar.setText("Tgl Keluar");

        lblStok.setText("Stok");

        btnUpdate.setText("Ubah");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblHarga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNama, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(tfHarga))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeluar)
                            .addComponent(lblStok))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfStok, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(tfKeluar))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeluar)
                    .addComponent(tfKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarga)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStok)
                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int status = 0;
        try {
            DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
            status = con.delete(new Barang(tfId.getText(), tfNama.getText(), Integer.parseInt(tfHarga.getText()), 
            tfMasuk.getText(), tfKeluar.getText(), Integer.parseInt(tfStok.getText())));
            refreshTable();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Barang Berhasil dihapus");
        } else {
            JOptionPane.showMessageDialog(this, "Barang Gagal dihapus");

        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int status = 0;
        try {
            DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
            status = con.update(new Barang(tfId.getText(), tfNama.getText(), Integer.parseInt(tfHarga.getText()), 
            tfMasuk.getText(), tfKeluar.getText(), Integer.parseInt(tfStok.getText())));

            refreshTable();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Data Barang Berhasil diubah");
        } else {
            JOptionPane.showMessageDialog(this, "Data Barang Gagal diubah");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        int selectedIndex = tblBarang.getSelectedRow();

        tfId.setText(model.getValueAt(selectedIndex, 0).toString());
        tfNama.setText(model.getValueAt(selectedIndex, 1).toString());
        tfHarga.setText(model.getValueAt(selectedIndex, 2).toString());
        tfMasuk.setText(model.getValueAt(selectedIndex, 3).toString());
        tfKeluar.setText(model.getValueAt(selectedIndex, 4).toString());
        tfStok.setText(model.getValueAt(selectedIndex, 5).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int status = 0;
        try {
            DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
            status = con.insert(new Barang(tfId.getText(), tfNama.getText(), Integer.parseInt(tfHarga.getText()), 
            tfMasuk.getText(), tfKeluar.getText(), Integer.parseInt(tfStok.getText())));
            refreshTable();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(BarangFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Barang Berhasil ditambahkan");
        } else {
            JOptionPane.showMessageDialog(this, "Barang Gagal ditambahkan");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
//        BarangModel model = (BarangModel)tblBarang.getModel();
//        String query = null;
//        query = "lower(nama) like '%"+tfCari.getText()+"%' ";
//        model.getRecDB(query);
//        if(model.getRowCount() > 0){tblBarang.setRowSelectionInterval(0,0);}
//        tblBarang.tableChanged(new javax.swing.event.TableModelEvent(model));
    }//GEN-LAST:event_btnCariActionPerformed

    private void lblHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblHomeActionPerformed
        
        HalamanMenu menu = new HalamanMenu();
        this.dispose();
        menu.setVisible(true);
        
    }//GEN-LAST:event_lblHomeActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JButton lblHome;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblMasuk;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStok;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfKeluar;
    private javax.swing.JTextField tfMasuk;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfStok;
    // End of variables declaration//GEN-END:variables

    private void populateDataToTable() throws SQLException {
       model = (DefaultTableModel) tblBarang.getModel();
       List<Barang> brg = con.loadBarang();
                for (Barang br : brg) {
                    Object[] row = new Object[6];
                    row[0] = br.getIdBarang();
                    row[1] = br.getNama();
                    row[2] = br.getHarga();
                    row[3] = br.getTglMasuk();
                    row[4] = br.getTglKeluar();
                    row[5] = br.getStok();
                    model.addRow(row);
        }
    }
}
