/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.unpas.psi.tubes.view;


import com.mysql.jdbc.Statement;

import id.ac.unpas.psi.tubes.controller.BarangController;
import id.ac.unpas.psi.tubes.model.data.BarangModel;
import id.ac.unpas.psi.tubes.model.pojo.Barang;
import id.ac.unpas.psi.tubes.utilities.DatabaseUtilities;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author SB604-15
 */
public class BarangKeluarFrame extends javax.swing.JFrame {
    BarangController con = new BarangController();
    private DefaultTableModel model;
    /**
     * Creates new form TabelMahasiswaFrame
     */
    public BarangKeluarFrame() throws SQLException {
        initComponents();
        populateDataToTable();
    }
    
    public void refreshTable() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        model.setRowCount(0);
        populateDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        btnCari = new javax.swing.JButton();
        tfCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cBulan = new javax.swing.JComboBox();
        lblBulan = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnPratinjau = new javax.swing.JButton();
        tfPratinjau = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_BARANG", "NAMA_BARANG", "HARGA_BARANG", "TGL_KELUAR", "STOK_BARANG"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        cBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cBulan.setToolTipText("");
        cBulan.setName(""); // NOI18N
        cBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBulanActionPerformed(evt);
            }
        });

        lblBulan.setText("Pilih Bulan:");

        btnCetak.setText("Cetak Data");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblBulan)
                .addGap(18, 18, 18)
                .addComponent(cBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnCetak)
                .addGap(47, 47, 47)
                .addComponent(btnReset)
                .addGap(43, 43, 43)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBulan)
                    .addComponent(btnCetak)
                    .addComponent(btnReset)
                    .addComponent(btnKembali))
                .addGap(26, 26, 26))
        );

        btnPratinjau.setText("Pratinjau");
        btnPratinjau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPratinjauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jScrollPaneLayout = new javax.swing.GroupLayout(jScrollPane);
        jScrollPane.setLayout(jScrollPaneLayout);
        jScrollPaneLayout.setHorizontalGroup(
            jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScrollPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jScrollPaneLayout.createSequentialGroup()
                        .addComponent(btnPratinjau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPratinjau, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jScrollPaneLayout.setVerticalGroup(
            jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScrollPaneLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCari)
                        .addComponent(btnPratinjau))
                    .addComponent(tfPratinjau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
        int selectedIndex = tblBarang.getSelectedRow();
    }//GEN-LAST:event_tblBarangMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
//        BarangModel model = (BarangModel)tblBarang.getModel();
//        String query = null;
//        query = "lower(nama) like '%"+tfCari.getText()+"%' ";
//        model.getRecDB(query);
//        if(model.getRowCount() > 0){tblBarang.setRowSelectionInterval(0,0);}
//        tblBarang.tableChanged(new javax.swing.event.TableModelEvent(model));
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        HalamanMenu menu = new HalamanMenu();
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBulanActionPerformed
        // TODO add your handling code here:
        if(cBulan.getSelectedItem().equals("Januari")) {
            DefaultTableModel model = (DefaultTableModel) tblBarang.getModel();
            int selectedIndex = tblBarang.getSelectedRow();
        } if(cBulan.getSelectedItem().equals("Februari")) {
                    JOptionPane.showMessageDialog(null, "Anda Telah Logout");
            }
    }//GEN-LAST:event_cBulanActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(
                    "src/id/ac/unpas/psi/tubes/report/barang_report.jasper",
                    null,
                    DatabaseUtilities.getConnection());
            JasperViewer.viewReport(jasperPrint, true);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException ex) {
            Logger.getLogger(BarangKeluarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnPratinjauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPratinjauActionPerformed
        // TODO add your handling code here:
        try {
            HashMap param = new HashMap();
            param.put("idText", "%"+tfPratinjau.getText()+"%");
            // idText adalah parameter pada template report
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(
                    "src/id/ac/unpas/psi/tubes/report/barang_param_report.jasper",
                    param,
                    DatabaseUtilities.getConnection());
             JasperViewer.viewReport(jasperPrint, true);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, e);
        } catch (SQLException ex) {
            Logger.getLogger(BarangKeluarFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPratinjauActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPratinjau;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cBulan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfPratinjau;
    // End of variables declaration//GEN-END:variables

    private void populateDataToTable() throws SQLException {
       model = (DefaultTableModel) tblBarang.getModel();
       List<Barang> brg = con.loadBarang();
                for (Barang br : brg) {
                    Object[] row = new Object[5];
                    row[0] = br.getIdBarang();
                    row[1] = br.getNama();
                    row[2] = br.getHarga();
                    row[3] = br.getTglKeluar();
                    row[4] = br.getStok();
                    model.addRow(row);
        }
    }
    
}
